# Generated by Django 5.1.1 on 2024-09-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Счётчик просмотров'),
        ),
    ]
